# Generated by Django 2.0.5 on 2018-05-22 14:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('guesses_allowed', models.IntegerField(default=10)),
                ('guesses_taken', models.IntegerField(default=10)),
                ('letters_available', django.contrib.postgres.fields.jsonb.JSONField(default=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'])),
                ('letters_guessed', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('guessed_word_state', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
                ('is_game_over', models.BooleanField(default=False)),
            ],
        ),
    ]
